### ISSUE TITLE
🗄️ [Documentation] - Showing cleared and uncleared bank balances isn't easily discoverable

### ISSUE THREAD

**Issue by Teprifer** [actualbudget/docs#11]
Creating from: https://github.com/actualbudget/releases/issues/241

The expando icon only shows on mouse over, this should be changed to always show so it's discoverable by new users, and possibly even default to showing the expanded balances to enhance awareness.

------
Can you clarify what you're looking for that's different from this?
![image](https://user-images.githubusercontent.com/4273797/159667574-c3c3667e-d0b6-4f4c-815f-2ad350f860fb.png)

_Originally posted by @MikeBishop in https://github.com/actualbudget/releases/issues/241#issuecomment-1076146400_

**Comment by rich-howell** [comment]
Hey @Teprifer 

Thanks for raising this, we are going to add this into our user documentation, which is being worked on [here](https://github.com/actualbudget/docs/pull/36)

Cheers
Rich
