### ISSUE TITLE
🗄️ [Documentation] - Editing "As Rule" scheduled transaction.

### ISSUE THREAD

**Issue by bpaulien** [actualbudget/docs#13]
When editing a scheduled transaction, you can either edit the data on the "front page" (typically amount is what changes for me) OR on the "Edit as Rule" page.  But if you try both only the "Edit as Rule" change actually sticks.

Example:
I have a scheduled transaction for natural gas payment.  As part of the schedule, I have notes set to "[Provider Name] - [MMM]" (first 3 letters of month for the invoice.) 

 I got an email stating that the next bill will be $88.  

- I edit the transaction (previous bill was $100, so I change that to $88).  
- Now I click on "Edit as Rule", and change the note to say "Mar".  
- Click Save on that screen
- Click save on the main schedule screen.  
- Now I look at the scheduled transaction, and it still says $100.  
- I edit it, and check the rule,  Note is set to "Mar" (as it should be)
- So I change the amount again, and save.  This time it sticks.

**Comment by rich-howell** [comment]
Hey @bpaulien 

Thanks for raising this, we have added this to the documentation which you can find here https://actualbudget.github.io/docs/Budgeting/schedules#how-to-use-rules-with-schedules.

Hope this helps, if not let us know and we will expand on it some more.

Cheers
Rich
