### ISSUE TITLE
⭐ [Documentation] - instruct the user to cd into directory with fly.toml

### ISSUE THREAD

**Issue by Jackenmen** [actualbudget/docs#140]
### Description

The **Deploying Actual on fly.io with a container image** document should clearly instruct the user that when running `fly launch` command (and commands after that), they need to be running them in the directory with fly.toml file that they created earlier.

For comparison, the **Deploying Actual** section of **Deploying Actual on fly.io with git** document actually does a lot better job of this by clearly showing how to navigate each step of the deployment process. I think it has a bit too many of too big screenshots but nonetheless, it makes it hard to do something wrong.

### Documentation URL

https://github.com/actualbudget/docs/blob/master/docs/Installing/fly/Fly-image.md

**Comment by tjex** [comment]
Let me know if I'm missing something, but it is stated in the first step of [persisting data](https://github.com/actualbudget/docs/blob/master/docs/Installing/fly/Fly-image.md#persisting-server-data) that you need to execute the commands in the same folder that has `fly.toml` in it.

Or are you specifically meaning at step 5 under 'deploying' that it should state there that you should be in the folder from where the fly.toml was created in step 3?

**Comment by Jackenmen** [comment]
> Or are you specifically meaning at step 5 under 'deploying' that it should state there that you should be in the folder from where the fly.toml was created in step 3?

That's what I mean, yes. The mention of it in the "Persisting server data" section should stay but it should also be noted in the "Deploying" section since it is an earlier step and until that point, nothing in the documented tells you that you should run the command from the directory of the created fly.toml file.
