### ISSUE TITLE
SharedArrayBuffer

### ISSUE THREAD

**Issue by p6002** [actualbudget/docs#149]
### Description

Nowhere in the documentation does it say what I should do. Add some entry in compose? Open it to the world in Traefik? Any manual changes? 
https://i.ibb.co/j40t4qq/2023-04-06-225828.png

### Documentation URL

https://actualbudget.github.io/docs/Troubleshooting/SharedArrayBuffer/

**Comment by j-f1** [comment]
The SharedArrayBuffer doc links to [Activating HTTPS](https://actualbudget.github.io/docs/Installing/HTTPS/) which should have some options and a step by step guide to fix this issue. Let me know if you run into any problems there and we can reopen!
