### ISSUE TITLE
🗄️ [Documentation] - Unable to delete transactions/ Schedules to Budget

### ISSUE THREAD

**Issue by jeanlst** [actualbudget/docs#15]
How can I delete transactions? I don't really understand why can't I manage EVERYTHING

I have monthly bills that I'm obligated to pay every month like rent, electricity, internet. How do I make Schedules that post the transaction(since its direct deposit) and automatically budget and make the payment?

**Comment by shall0pass** [comment]
I think this issue is resolved with the content of this section: https://actualbudget.github.io/docs/Accounts/Transactions/bulk-editing-transactions

The page isn't found when doing a search for "delete".  It'd be worth looking into adding keywords to some pages to make them more discoverable.

**Comment by rich-howell** [comment]
Hey @jeanlst 

This is resolved, looks like we have some documentation for this here https://actualbudget.github.io/docs/Accounts/Transactions/bulk-editing-transactions

Cheers
Rich
