### ISSUE TITLE
⭐ [Documentation] - fly update best practice

### ISSUE THREAD

**Issue by tjex** [actualbudget/docs#156]
### Description

In the actual-server repo's readme it's stated:

> Whenever you want to update Actual, update the versions of @actual-app/api and @actual-app/web in package.json and run flyctl deploy.

But in the docs ([website](https://actualbudget.github.io/docs/Installing/fly/Fly-updating)) there is a process to pull changes from the repo and then redeploy. 

Is there a case where one is a better option to document? 
ie, should the readme instruction be changed to that of the docs, or the other way around?

### Documentation URL

https://actualbudget.github.io/docs/Installing/fly/Fly-updating

**Comment by rich-howell** [comment]
> Whenever you want to update Actual, update the versions of @actual-app/api and @actual-app/web in package.json and run flyctl deploy.

This won't include any changes to the server. We deploy using Actual Server and by default that gets the latest version of Web from NPM. 

If you have deployed without Docker I think the documentation instructions are more complete.

**Comment by rich-howell** [comment]
This will be resolved by #127
