### ISSUE TITLE
⭐ [Documentation] - Update filter page for info about saved filters

### ISSUE THREAD

**Issue by Shazib** [actualbudget/docs#222]
### Description

https://actualbudget.org/docs/budgeting/filters#how-to-use-the-filter-tool

Updates should probably wait till that features goes live.

### Documentation URL

https://actualbudget.org/docs/budgeting/filters#how-to-use-the-filter-tool

**Comment by migillett** [comment]
I can start work on this.

**Comment by migillett** [comment]
PR Created: https://github.com/actualbudget/docs/pull/232
