### ISSUE TITLE
⭐ [Documentation] - Settings page images missing highlighted callouts

### ISSUE THREAD

**Issue by migillett** [actualbudget/docs#236]
### Description

Issue:
this section has screenshots, but the sections in question are not highlighted. For instance, when it mentions `Encryption`, all that it shows it just a full screenshot.

Fix:
either crop the images or add in way to highlight the specific area of the image.

### Documentation URL

https://github.com/actualbudget/docs/blob/master/docs/tour/settings.md

**Comment by migillett** [comment]
PR created https://github.com/actualbudget/docs/pull/249

**Comment by j-f1** [comment]
Thanks! In the future, if you say “fixes #236” in the description of the PR (not the title) it will automatically close the issue when the PR is merged.
