### ISSUE TITLE
⭐ [Documentation] - Move Filter Notes to more appropriate heading 

### ISSUE THREAD

**Issue by Kidglove57** [actualbudget/docs#237]
### Description

I have long felt that the Filter explanation notes do not fit well under the heading  “Budgeting” in the Documentation. Personally, I use Filters to create bespoke tabular reports, which I am so glad we can now save. What I propose is this :
1) Change the documentation heading from “Reports” to “Reports and Filters”. 
2) Move the notes explaining Filters from “Budgeting” to “Reports and Filters”.

If there are no strong objections or compelling alternatives, I will raise a PR.

### Documentation URL

https://actualbudget.org/docs/budgeting/filters#how-to-use-the-filter-tool

**Comment by j-f1** [comment]
Sure! I think it makes sense either under “Reports” or maybe as a top level page. I do want to make sure that people realize that they can use filters when they’re viewing their transactions, but perhaps the button in the UI will be clear enough that they’ll go looking for more info.

**Comment by j-f1** [comment]
The sidebar is defined here: https://github.com/actualbudget/docs/blob/master/docs-sidebar.js. Happy to help out if you’re having trouble editing that file.

**Comment by migillett** [comment]
I can tackle this one.

**Comment by migillett** [comment]
[Created PR.](https://github.com/actualbudget/docs/pull/238) I'm currently trying to sort out how to get this working locally to I can test. Any tips? Windows is fighting me.

**Comment by Kidglove57** [comment]
Thank you so much. I have left a comment under the PR.

**Comment by migillett** [comment]
Fixed!

**Comment by j-f1** [comment]
Fixed in #238. Thanks, @migillett!
