### ISSUE TITLE
⭐ [Documentation] - Error in Keyboard Shortcut Notes

### ISSUE THREAD

**Issue by Kidglove57** [actualbudget/docs#239]
### Description

Under Tips and Tricks we list a number of Keyboard Shortcuts. I cannot make the Global Shortcuts work, that are listed at the beginning of these notes. Cmd 1 etc. I believe they may relate to the old hosted Actual?

Is anyone else able to make these work? I have tried on Mac and Windows. If they no longer function, these notes should be removed.

### Documentation URL

https://actualbudget.org/docs/getting-started/tipstricks

**Comment by shall0pass** [comment]
`CTRL + O`  works for me, but `CTRL 1`, `CTRL 2`, and `CTRL 3` do not.

Is this something that needs removed or a bug report filed to have the functionality put back?

**Comment by j-f1** [comment]
They may only work in the Electron app since the browser reserves some shortcuts for itself (Cmd/Ctrl plus a number often switch you to a different tab)

**Comment by Kidglove57** [comment]
Thanks @j-f1 
I have now tested in the Mac Electron app. The Keyboard Shortcuts do indeed work there EXCEPT CMD (or CTRL) 0.

I cannot get any of them to work in Firefox on Mac (due as you say to other keyboard commands already in use).

I'll do a PR to add a suitable note to the documentation

**Comment by shall0pass** [comment]
I tested on the Windows electron app, along with Brave/Chrome this morning and the 1, 2, and 3 didn't work in either.  @Kidglove57, are you trying an O, as in Orange, and not a 0 (zero)?  The O (Orange) is the only one that worked for me.

**Comment by Kidglove57** [comment]
Thanks @shall0pass. I had indeed read that worong and was using 0 (Zero). Yes, O (Orange does work for me)!
