### ISSUE TITLE
⭐ [Documentation] - Fly.io

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/docs#296]
### Description

I think it would be a good idea to inform people of this https://community.fly.io/t/we-are-going-to-start-charging-for-dedicated-ipv4-in-january-1st/15970 because this comment on the docs page for Actual `If you follow the steps in this guide, you will remain well within the free plan limits. For more details, check out [Fly’s pricing documentation](https://fly.io/docs/about/pricing/)` is no longer true. 

### Documentation URL

https://actualbudget.org/docs/install/fly

**Comment by tjex** [comment]
Although, it does say for new apps, that no unexpected charges will be had.

> New apps have been getting shared IPv4 when first deployed for a while, your new apps should be good to go with no unexpected charges. Also, just creating an app doesn’t assign IPs immediately.

Also on the fly pricing site:

> Each application receives a [shared IPv4 address](https://fly.io/docs/reference/services/#shared-ipv4) and unlimited [Anycast IPv6](https://fly.io/docs/reference/services/#ipv6) addresses for global load balancing.

> Dedicated IPv4 addresses are $2/mo.

As the install/fly doc is for new setups, and it appears like new apps will get a shared ipv4 (free of charge), maybe it doesn't need to change?

**Comment by tjex** [comment]
And actually, my fly instance, made last year, already has a  shared ipv4.
So yeah, it seems like the news is about dedicated ipv4 that will now cost, but that used to be free? 🧐

Or am I missunderstanding / overlooking something?

**Comment by tjfinlinson** [comment]
This probably just need a little bit of clarification on the docs page and making sure it's in alignment with what fly.io says about it.

**Comment by bruno-cobucci** [comment]
As someone who is coming to Actual, I also felt confused when reading the docs. The thing is, there used to be a free plan in Fly.io - that's even written in the docs: 

> If you follow the steps in this guide, you will remain well within the free plan limits.

But, in a recent change, there's no more a free plan. The default, start plan is the "Hobby plan", which costs a minimum of $5/month. See [this discussion](https://community.fly.io/t/i-got-charged-today-for-the-hobby-plan-and-im-confused-as-to-why-cause-fly-io-didnt-send-any-emails/17969/3), for example.

Maybe the docs should be updated to adress this change in Fly.io. Specially considering that this error is in the main "Installing Actual" section.

**Comment by tjex** [comment]
It should be updated, I agree, but it's still technically "free" for the use case of Actual. As the initial sign up gets you $5 credit *given* to you (not debited), and is only used up when you exceed the free allowances:

> When you sign up for a Fly.io account, we create a default (“personal”) organization for you, which receives a one-time $5 sign-up credit to let you test-drive Fly.io at no cost. This organization’s $5/month Hobby plan subscription does not start until the credit has been used up. Usage that falls outside of our free resource allowances consumes your sign-up credit.

Resources included for free on all plans:

- Up to 3 shared-cpu-1x 256mb VMs
- 3GB persistent volume storage (total)
- 160GB outbound data transfer

Additional resources are billed at the usage-based pricing detailed below.

**Comment by tjex** [comment]
I've commented in the fly.io thread asking for clarification. I'll make a pr for an interim addition to the documentation until this gets clarified, to avoid any new users of Fly getting stung with a $5 debit.

**Comment by tjex** [comment]
Fly answered my question on the forum, and it does cost now $5 per month as a base fee. I've updated the PR #311  to reflect this.
