### ISSUE TITLE
⭐ [Documentation] - Suggestion to Improve the home page

### ISSUE THREAD

**Issue by codewithdev** [actualbudget/docs#301]
### Description

I feel the home page and the content can be improved a bit for more readability and clarity. 

Link: https://actualbudget.org/docs/

Where the changes are required: 

👇
<img width="933" alt="image" src="https://github.com/actualbudget/docs/assets/44609609/f46f1706-dedd-4cbb-abaa-1aa90a6b3190">

Let me know, if I should raise a PR with the updated home page?

### Documentation URL

https://actualbudget.org/docs/

**Comment by rich-howell** [comment]
A PR is generally a good first step to demonstrate your proposal, given that this issue doesn't really outline what your planning or suggesting is changed.

**Comment by codewithdev** [comment]
#355

**Comment by wdpk** [comment]
can be closed?
