### ISSUE TITLE
Documentation error: Server requires Node 18+ but documentation says 16

### ISSUE THREAD

**Issue by warenzema** [actualbudget/docs#334]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The [Local Installation](https://actualbudget.org/docs/install/local) instructions say that Node 16 is required, but it looks like last November that was upgraded to Node 18 as the min version.

Docs:
> Actual Server currently requires at least Node.js v16.

Terminal:
> Usage Error: This tool requires a Node version compatible with >=18.12.0 (got 16.20.2). Upgrade Node, or set `YARN_IGNORE_NODE=1` in your environment.

I would try to report it to the documentation repo, but I'm not sure where that is, as I just learned about Actual Budget today and started playing around and ran into this minor mismatch, so wanted to report it somewhere before I installed 18 and forgot to tell anyone.

### Where are you hosting Actual?

Locally via Yarn

### Operating System

Linux

**Comment by MatissJanis** [comment]
Makes sense. PRs are more than welcome.
