### ISSUE TITLE
🐛 [BUG] - Can't lower the budgeted amount to take away from the budget

### ISSUE THREAD

**Issue by hayoken2000** [actualbudget/docs#347]
### Description

I am trying to remove some money from a budgeted category and it keeps erroring out and telling me to submit a request on github.
![Screenshot 2024-04-09 192011](https://github.com/actualbudget/docs/assets/65980749/8500b47e-ae4d-4b95-9e49-77e29801241f)
![Screenshot 2024-04-09 191956](https://github.com/actualbudget/docs/assets/65980749/9394be24-e50a-4b3f-bb45-b290294594a4)

### Reproduction URL

https://github.com/actualbudget

### Reproduction steps

```bash
1. Go to Budget
2. click on the amount budgeted 
3. enter a lower amount
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Firefox

**Comment by shall0pass** [comment]
Please resubmit this to the 'https://GitHub.com/actualbudget/actual' repo.
