### ISSUE TITLE
🗄️ [Documentation] - Describe how the filters work on the account screen

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/docs#37]
### Description

Explain how the filters work on the account screen and how each successive filter builds on the previous filter.  This could be an improvement to other accounts page documentation that exists.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Category

Budgeting

**Comment by rich-howell** [comment]
kidglove57 is going to have a look at this one

**Comment by Kidglove57** [comment]
Kidglove57 has provided a draft help note for review and posting
