### ISSUE TITLE
⭐ [Documentation] - Improve Local Installation Pages

### ISSUE THREAD

**Issue by codewithdev** [actualbudget/docs#387]
### Description

Opening an issue to reference the pages that needs some improvement and reduce content complexity, content structure, and information provided in the docs. This will help users to find the information as quickly as they run "ls" command in their CLI. 😄 

For example, the Local installation page can have bullet points. 

![image](https://github.com/actualbudget/docs/assets/44609609/25e7c659-1469-4ea9-aede-4f28c9d1582e)

Will raise respective PRs to support this changes. 

### Documentation URL

https://actualbudget.org/docs/install/local

**Comment by codewithdev** [comment]
I realised there is so much unnecessary information provided on this page https://actualbudget.org/docs/install/local.

**Comment by RubenOlsen** [comment]
@codewithdev, if you are not a developer but a user, what exactly is unnecessary on that page?

Remember that when writing documentation, one must assume that the reader does not necessarily have the same background as oneself.

**Comment by codewithdev** [comment]
As a developer, I think whoever (user) using a particular application, they should be aware of common practices of cloning repository, fetching latest commits from upstream, and running localhost. I don't think these kind of information should be added in the documentation, as they are generally available for public and spread over internet.

**Comment by RubenOlsen** [comment]
This has been addressed and is now published.
