### ISSUE TITLE
🗄️ [Documentation] - Bulk Transaction Editing

### ISSUE THREAD

**Issue by Kidglove57** [actualbudget/docs#39]
### Description

The bulk editing function for transactions is both powerful and useful. I will have a go at drafting some documentation

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Category

Budgeting

**Comment by Kidglove57** [comment]
Kidglove57 has provided a draft help note for review and posting

**Comment by shall0pass** [comment]
There are some unexpected behaviors when bulk editing includes split transactions.  We will probably want to point that out as a caution.

**Comment by Kidglove57** [comment]
Thanks - yes indeed. I am thinking that we should add a warning to the draft help file (with Rich for review) to say that splits should be edited individually and not as part of a bulk edit.
