### ISSUE TITLE
⭐ [Documentation] - Provide basics of a text style guide to aid contributors in using one shared voice

### ISSUE THREAD

**Issue by wdpk** [actualbudget/docs#399]
### Description

Provide a little more guidance on how to write text so that all contributors are contributing similar sort of content to the shared repo.

Open to thoughts.

Fixed by #398 

### Documentation URL

https://github.com/actualbudget/docs/blob/master/README.md

**Comment by atgrey24** [comment]
I made a [comment ](https://github.com/actualbudget/docs/pull/398#issuecomment-2236515580) over on the PR #398 page. Note sure which location you'd prefer to keep the discussion.

**Comment by RubenOlsen** [comment]
This has now been published - closing issue.
