### ISSUE TITLE
How to Show Running Balance

### ISSUE THREAD

**Issue by Kidglove57** [actualbudget/docs#40]
### Description

Many first time users miss the option to show running balance in an account register.
Help note to be drafted to explain this

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Category

Accounts

**Comment by Kidglove57** [comment]
Kidglove57 will provide a draft help note for review and posting

**Comment by shall0pass** [comment]
This is the relevant section to consider.
https://actualbudget.github.io/docs/Getting-Started/tipstricks#show-running-balances

**Comment by Kidglove57** [comment]
Perfect - one less for me to draft. Thank you
