### ISSUE TITLE
🗄️ [Documentation] - Reconcilation

### ISSUE THREAD

**Issue by Kidglove57** [actualbudget/docs#41]
### Description

A brief note is needed in the Help files to explain the  Reconciliation option. This is not all that users expect it to be and their expectations of it should be managed

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Category

Accounts

**Comment by Kidglove57** [comment]
Kidglove57 will provide a draft help note for review and posting

**Comment by shall0pass** [comment]
This is the page to edit for Reconciliation.
https://actualbudget.github.io/docs/Budgeting/reconcile

**Comment by Kidglove57** [comment]
Thank you for pointing that out! I was briefly discussing with Rich earlier and we did not find at that time. I will close this.
