### ISSUE TITLE
⭐ [Documentation] - Simple FIN Bank Sync Article modification

### ISSUE THREAD

**Issue by zanthium** [actualbudget/docs#452]
### Description

At the top of the document it advertises that this is experimental but advises that the functionality may not be available for latest releases. After discussions were had in the Discord it is actually available under More>Settings>Advanced Settings>and there is an acknowledgement to enable experimental feature. 

### Documentation URL

https://actualbudget.org/docs/experimental/simplefin-sync/#simplefin-setup

**Comment by RubenOlsen** [comment]
Good catch. Thank you for this. I will amend the documentation accordingly.
