### ISSUE TITLE
🗄️ [Documentation] - SimpleFIN now released from experimental

### ISSUE THREAD

**Issue by matt-fidd** [actualbudget/docs#454]
### Description

Sync via SimpleFIN was released from experimental with https://github.com/actualbudget/actual/pull/3459 so the docs will need moving out of the experimental section before the next release.

I'm not sure where the best place for them is, a couple of ideas:
1. Everything on the current "Accounts & Transactions -> Connecting Your Bank" page is moved under a "GoCardless" heading
2.  "Accounts & Transactions -> Connecting Your Bank" becomes a menu (if possible) and then UK/EU (GoCardless) is separated from US (SimpleFIN) more obviously for readers

2 is probably cleanest IMO

### Category

Accounts, Installation & Configuration

**Comment by matt-fidd** [comment]
This would be good to get in before the next release goes live so that the docs stay current to the latest version if anyone wants to take a crack?

**Comment by Jonathan-Fang** [comment]
How soon is the next release going live? I could try.

I was thinking making the Connecting Your Bank a dropdown and then you can go between Simplefin and GoCardless.

**Comment by matt-fidd** [comment]
@Jonathan-Fang will be pretty soon, probably the 1st 2nd or 3rd of October

I also prefer the dropdown method

Whatever works for you! With documentation, doing it on Github online is probably alright, but personally I make all of my changes from local.

**Comment by Jonathan-Fang** [comment]
Sounds good, I'll start working on it.

I'll figure out how to use the local thing next time, I don't know how to use yarn with git bash.

**Comment by Jonathan-Fang** [comment]
Should I create a pull request right now or wait until I have everything ready? I see lots of WIP in the pull requests, but I also see that the docs say that they prefer the pull request to be complete before submitting it.

**Comment by matt-fidd** [comment]
It's up to you, we won't review it until you mark it as ready by removing the "[WIP]" prefix from the pull request title.
It's easier to get help through a PR but if you're happy with what you're doing then we'd probably ask that you left it until you were pretty much ready to open.
