### ISSUE TITLE
 api.runWithBudget is not a function

### ISSUE THREAD

**Issue by 7aklhz** [actualbudget/docs#52]
I'm trying to get the API to work. Here is what I've done
1- I've installed actual-server locally and it's running on port 5006
2- I cd into the folder and installed the api using yarn add @actual-app/api
3- I created a test.js file in the actual-server folder and copy paste the following code
`let api = require('@actual-app/api');
async function run() {
  let budget = await api.getBudgetMonth('2019-10');
  console.log(budget);
}
api.runWithBudget('My-Budget', run);`
4- I updated "My-Budget" with my id
5- I run using node test.js and get the following error

`TypeError: api.runWithBudget is not a function`

Can you please advise ?

**Comment by rich-howell** [comment]
Moved this to documentation to build out some more examples around this as the issue itself isn't actually an issue but rather a call for advice.

**Comment by JamesHenry** [comment]
@rich-howell I'm confused as to why this isn't an issue? I ended up here because the documentation website gives out of date instructions, that's an issue with the docs, right?

The docs currently tell you to use `runWithBudget` which doesn't exist: 

https://github.com/actualbudget/docs/blob/master/docs/Developers/using-the-API.md

The comment above does not seem to be applicable anymore either: https://github.com/actualbudget/docs/issues/52#issuecomment-1295347702

Because https://github.com/actualbudget/actual/blob/master/docs/API.md does not exist.

Are there any up to date docs for how to use the API please?

**Comment by j-f1** [comment]
Here’s the docs from when that comment was posted: https://github.com/actualbudget/actual/blob/HEAD@%7B2022-09-22T12:05:27Z%7D/docs/API.md

**Comment by JamesHenry** [comment]
Thanks @j-f1, do you have any idea how to figure out the value to give to `dataDir`? I am just running the actual-server repo locally... 

This is my first time getting reacquainted with the project since the switch to OSS

**Comment by j-f1** [comment]
Working on updating the docs, it’s a bit complicated and I think the API package needs some improvements to make things easier.

**Comment by j-f1** [comment]
The `dataDir` should be the `user-files` dir of the server.

**Comment by JamesHenry** [comment]
@j-f1 that is what I had guessed but it doesn't seem to work...

Again this is a fresh installation, I have not done anything custom AFAIK

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/900523/212476658-2777e884-ecad-4d72-a299-e394667184d9.png">

<img width="543" alt="image" src="https://user-images.githubusercontent.com/900523/212476669-41158012-b256-499d-96e2-ea3ff837ae55.png">

**Comment by j-f1** [comment]
Try the Sync ID instead.

**Comment by JamesHenry** [comment]
@j-f1 sadly not! Hopefully you or one of the other maintainers wouldn't mind trying to repro with a fresh copy of `actual-server` some time next week

**Comment by JamesHenry** [comment]
Thanks so much @j-f1, sorry for the delay. I will set aside some time this weekend to try this out and let you know!

**Comment by MatissJanis** [comment]
This should be fixed. Closing
