### ISSUE TITLE
🗄️ [Documentation] - Create Account: Off-budget checkmark resets when account type is changed

### ISSUE THREAD

**Issue by bpaulien** [actualbudget/docs#54]
I was creating a new account, and had selected "off budget", then went back to change the type.  Then I hit "Create" and it made it an on budget account.

I went back and tried again.  This time I noticed that when I changed the type, the checkmark in "Off-budget" disappeared.  I think it should remember what I selected, if I wanted it off budget, even if I then realized I had the wrong type.

**Comment by rich-howell** [comment]
This seems to be related to the type of account you select, some are off budget and selecting between them changes the check box. 

This needs documenting.

**Comment by shall0pass** [comment]
I'm not sure I understand what is being asked?  Is there a way I'm not aware of to change the nature of an account between on and off budget?  Or is the question around the default settings in the dialog box that prompts for the account properties?
