### ISSUE TITLE
🗄️ [Documentation] - Posting Scheduled Transaction Early

### ISSUE THREAD

**Issue by mkemen** [actualbudget/docs#55]
I often post my scheduled transactions a day or two early.   When I select a transaction and choose to post it, it still is appearing in the upcoming scheduled transactions list.   If something is scheduled for 11/18 and I post it on 11/16, it should then set next scheduled date for 12/18.

Perhaps I am doing something wrong.  Help me out.

**Comment by shall0pass** [comment]
Please review/comment/edit [the PR #56](https://github.com/actualbudget/docs/pull/56) for accuracy and whether this resolves this issue.  Thanks,

**Comment by rich-howell** [comment]
@MatissJanis @j-f1 can you close this, @shall0pass PR #56 appears to have been merged and resolves.
