### ISSUE TITLE
🐛 [BUG] - prev and next page on the budgeting categories page point to the same url

### ISSUE THREAD

**Issue by kaichevannes** [actualbudget/docs#585]
### Description

The previous and next page both point to the how budgeting works page (https://actualbudget.org/docs/budgeting/)

### Reproduction URL

https://actualbudget.org/docs/budgeting/categories/

### Reproduction steps

```bash
1. Go to https://actualbudget.org/docs/budgeting/categories/
2. Scroll down to the bottom of the page
3. Prev and next pages are the same
```

### Screenshots

```bash
![image](https://github.com/user-attachments/assets/66d84782-4352-4c28-915c-5cc151d327bf)
```

### Browsers

Firefox

**Comment by quarklark** [comment]
Looks like it may be an issue with the index file for this section:

<img width="957" alt="image" src="https://github.com/user-attachments/assets/895276e8-f782-48ee-87e7-bfd72ac60f7a" />
