### ISSUE TITLE
🐛 [BUG] - Credit cards and returns/reimbursements links are greyed and not clickable

### ISSUE THREAD

**Issue by dryerflyer** [actualbudget/docs#66]
### Description

Inspecting the code, they do not have a link associated with them.

### Reproduction URL

https://actualbudget.com/docs/other/rules/

### Reproduction steps

```bash
1. Go to https://actualbudget.com/docs/other/rules/
2. Click on Credit cards
3. See nothing happen
```

### Screenshots

![image](https://user-images.githubusercontent.com/3928104/209989842-13fd22b3-8862-4178-840a-9ce75c8562a2.png)

### Browsers

Chrome

**Comment by rich-howell** [comment]
Hey @dryerflyer 

These docs are for the closed source version which this repo doesn't maintain. 

These are for https://actualbudget.github.io/docs/ 

Hope this helps
Cheers
Rich

**Comment by dryerflyer** [comment]
Sorry, I somehow missed that connection. That makes total sense then, why things didn't match what I was seeing.
