### ISSUE TITLE
🐛 [BUG] - Untitled field in sidebar at the bottom

### ISSUE THREAD

**Issue by dryerflyer** [actualbudget/docs#67]
### Description

There is an untitled link at the very bottom of the list. This should not exist in a production environment?

### Reproduction URL

https://actualbudget.com/docs/overview/getting-started/

### Reproduction steps

```bash
1. Go to https://actualbudget.com/docs/overview/getting-started/
2. Look at the left side-bar
3. See Untitled at the bottom
```

### Screenshots
![image](https://user-images.githubusercontent.com/3928104/209990248-8dcde1a9-b687-41d9-b1d6-3fba71a917cb.png)

### Browsers

Chrome

**Comment by rich-howell** [comment]
Hey @dryerflyer 

These docs are for the closed source version which this repo doesn't maintain. 

These are for https://actualbudget.github.io/docs/ 

Hope this helps
Cheers
Rich
