### ISSUE TITLE
🐛 [BUG] - Reconciliation not showing

### ISSUE THREAD

**Issue by dryerflyer** [actualbudget/docs#68]
### Description

Looking at the code and looking at the site served at the actualbudget url doesn't seem to match up? 
Reconciliation does not exist in the sidebar, yet in the code it is there:

```
    {
      type: 'category',
      label: 'Accounts',
      collapsed: true,
      items: [
        'Accounts/overview',
        'Accounts/addaccount',
        'Accounts/reconcile',
        {
          type: 'category',
          label: 'Transactions',
          collapsed: true,          
          items: [
            'Accounts/Transactions/importing-trans',
            'Accounts/Transactions/bulk-editing-transactions',
          ],
        },        
        unavailable('Connecting Your Bank'),
        'Accounts/payees',
        'Accounts/transfers',
      ],
    },
```

![image](https://user-images.githubusercontent.com/3928104/209990956-9d39864c-cb5c-47c7-a195-dab858eb745b.png)

Maybe this is a dupe of one of the others I opened..

### Reproduction URL

https://actualbudget.com/docs/accounts/overview/

### Reproduction steps

```bash
1. Go to https://actualbudget.com/docs/accounts/overview/
2. See the sidebar
3. There is no reconciliation
```

### Browsers

Chrome

**Comment by rich-howell** [comment]
Hey @dryerflyer 

Them docs are for the closed source version, the docs you are looking for are here https://actualbudget.github.io/docs/Accounts/reconcile 

Hope this helps
Cheers
Rich
