### ISSUE TITLE
⭐ [Documentation] - Rules

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/docs#83]
### Description

Documentation needs amending to include this https://github.com/actualbudget/actual/pull/482

### Documentation URL

https://github.com/actualbudget/docs/blob/master/docs/Budgeting/rules/rules.md

**Comment by tjex** [comment]
hey rich. I can attend to this along with additions I'll make from issue #85 .
two birds with one actual-stone.

**Comment by rich-howell** [comment]
> hey rich. I can attend to this.

Thank you so much.

**Comment by tjex** [comment]
hey @rich-howell . The documentation already mentions the ability to set 'cleared' status.

> Actions can set the following fields:
> 
>     payee
>     notes
>     date
>     amount
>     category
>     account
>     cleared

I could add some pictures though where it may help make things clearer. 

Also, this page almost only gives instruction for the desktop app. 
Do you guys still support the desktop app?
If not, should I remove the desktop app instructions, or add for the web app (in addition to the desktop app instructions)?

**Comment by rich-howell** [comment]
> hey @rich-howell . The documentation already mentions the ability to set 'cleared' status.
> 
> > Actions can set the following fields:
> > ```
> > payee
> > notes
> > date
> > amount
> > category
> > account
> > cleared
> > ```
> 
> I could add some pictures though where it may help make things clearer.
> 
> Also, this page almost only gives instruction for the desktop app. Do you guys still support the desktop app? If not, should I remove the desktop app instructions, or add instructions for the web app alongside?

Sorry for the delayed reply, took some time away from the project. 

Desktop App is staying I think, it isn't working at the moment but @MatissJanis said last time I spoke that it is something they want to get working, so them instructions will need to stay.

Thanks for your contributions.
