### ISSUE TITLE
⭐ [Documentation] - Using Actual

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/docs#85]
### Description

Better images are required 
We will need to update this to include https://github.com/actualbudget/actual/pull/459

### Documentation URL

Various pages in the Using Actual section

**Comment by tjex** [comment]
hey rich. I can start looking at this.
Will PR as I have some changes.

**Comment by rich-howell** [comment]
> hey rich. I can start looking at this. Will PR as I have some changes.

Brilliant, thank you so much

**Comment by tjex** [comment]
@rich-howell would you say we can close this issue?
